# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P85B66pe59XvP8FGL6Et4godzS0xNpan
"""

import os
import pickle
import torch
import nltk
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split
from nltk.tokenize import word_tokenize
from tqdm import tqdm
import speech_recognition as sr
import gradio as gr

nltk.download('punkt')
nltk.download('punkt_tab')

class TextDataset(Dataset):
  def __init__(self, csv_file):
    # For Hugging Face deployment, upload the CSV to your repo and use local path
    self.df = pd.read_csv(csv_file, encoding='latin1')
    self.texts = self.df['text'].values
    self.label = self.df['label'].values
    self.cache_file_path = 'token_cache.pkl'

    print('Tokenizing Text...')
    self.tokenize_text()

    print('Creating Vocab...')
    self.vocab = self.create_vocab(self.tokens)

    print('Preparing Text...')
    self.prepared_text_data = [self.encode_tokens(token_list) for token_list in self.tokens]

  def tokenize_text(self):
    if os.path.exists(self.cache_file_path):
      self.tokens = self.load_tokens()
    else:
      self.tokens = [word_tokenize(text.lower()) for text in tqdm(self.texts, desc='Tokenizing')]
      self.save_tokens(self.tokens)

  def __len__(self):
    return len(self.df)

  def __getitem__(self, idx):
    encoded_text = self.prepared_text_data[idx]
    label = self.label[idx]
    return torch.tensor(encoded_text), torch.tensor(label)

  def create_vocab(self, tokens):
    vocab = {}
    for token_list in tokens:
      for token in token_list:
        if token not in vocab:
          vocab[token] = len(vocab) + 1
    return vocab

  def encode_tokens(self, tokens):
    return [self.vocab.get(token, 0) for token in tokens]

  def save_tokens(self, tokens):
    with open(self.cache_file_path, 'wb') as f: pickle.dump(tokens, f)

  def load_tokens(self):
    with open(self.cache_file_path, 'rb') as f: return pickle.load(f)

class GRUClassifier(nn.Module):
  def __init__(self, embedding_dim, hidden_dim, vocab_size, output_size, num_layers=1):
    super(GRUClassifier, self).__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.rnn = nn.GRU(embedding_dim, hidden_dim, num_layers, batch_first=True)
    self.fc = nn.Linear(hidden_dim, output_size)

  def forward(self, x):
    embedded = self.embedding(x)
    _, rnn_hidden = self.rnn(embedded)
    out = self.fc(rnn_hidden[-1])
    return out

def collate_fn(batch):
  texts, labels = zip(*batch)
  texts_tensor = torch.nn.utils.rnn.pad_sequence(texts, batch_first=True)
  labels_tensor = torch.tensor(labels)
  return texts_tensor, labels_tensor

# Main execution logic
if __name__ == '__main__':
  # Adjust path for Hugging Face or local Colab usage
  dataset_path = 'Stress.csv' if os.path.exists('Stress.csv') else '/content/drive/MyDrive/Stress.csv'

  if os.path.exists(dataset_path):
    dataset = TextDataset(dataset_path)
    vocab_size = len(dataset.vocab) + 1
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = GRUClassifier(200, 128, vocab_size, 2, 6).to(device)

    # Note: Training code is omitted for brevity in inference, assume model is loaded/trained here

    def predict_with_gru(text_input):
      if not text_input.strip(): return 'Empty input', '0%'
      tokens = word_tokenize(text_input.lower())
      encoded = torch.tensor([dataset.vocab.get(t, 0) for t in tokens]).unsqueeze(0).to(device)
      model.eval()
      with torch.no_grad():
        outputs = model(encoded)
        probs = torch.softmax(outputs, dim=1)
        conf, pred = torch.max(probs, 1)
      res = 'Stress Detected' if pred.item() == 1 else 'No Stress Detected'
      return res, f'{conf.item()*100:.2f}%'

    def predict_stress_audio(audio_input):
      r = sr.Recognizer()
      with sr.AudioFile(audio_input) as source:
        audio = r.record(source)
      text = r.recognize_google(audio)
      return predict_with_gru(text)

    text_if = gr.Interface(fn=lambda x: predict_with_gru(x), inputs="text", outputs=["text", "text"])
    audio_if = gr.Interface(fn=predict_stress_audio, inputs=gr.Audio(type='filepath'), outputs=["text", "text"])
    gr.TabbedInterface([text_if, audio_if], ['Text', 'Audio']).launch()