# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYmSqFpmM61jjuNOPIVeA9nJ_7HlRzeF
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import speech_recognition as sr
import gradio as gr
import streamlit as st

df = pd.read_csv('Stress.csv', encoding='latin1')

df['text'] = df['text'].str.strip()

X, y = df['text'], df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

vec = CountVectorizer(stop_words='english', lowercase=True)
vec.fit(X_train)
X_train_dt = vec.transform(X_train)

model = MultinomialNB()
model.fit(X_train_dt.toarray(), y_train)

def predict_stress_text(text_input):
  text_input_dt = vec.transform([text_input.strip()])
  text_pred = model.predict(text_input_dt.toarray())
  text_proba = model.predict_proba(text_input_dt.toarray()).max()
  confidence = f'{text_proba*100}%'

  if text_pred == 1:
    result = 'Psychological Stress Detected'
  else:
    result = 'No Psychological Stress Detected'

  return result, confidence

def predict_stress_audio(audio_input):
  r = sr.Recognizer()
  with sr.AudioFile(audio_input) as source:
    audio = r.listen(source)
  audio_text = r.recognize_google(audio, language='en-US').strip()
  audio_input_dt = vec.transform([audio_text])
  audio_pred = model.predict(audio_input_dt.toarray())
  audio_proba = model.predict_proba(audio_input_dt.toarray()).max()
  confidence = f'{audio_proba*100}%'

  if audio_pred == 1:
    result = 'Psychological Stress Detected'
  else:
    result = 'No Psychological Stress Detected'

  return result, confidence

text_interface = gr.Interface(
    fn = predict_stress_text,
    inputs = gr.Textbox(label='Text Input', placeholder='Type here...', lines=7),
    outputs = [gr.Textbox(label='Result'), gr.Textbox(label='Confidence')],
    title = 'Psychological Stress Detection',
    description = 'Input text to check for signs of psychological stress'
)

audio_interface = gr.Interface(
    fn = predict_stress_audio,
    inputs = gr.Audio(label='Audio Input', type='filepath'),
    outputs = [gr.Textbox(label='Result'), gr.Textbox(label='Confidence')],
    title = 'Psychological Stress Detection',
    description = 'Input audio to check for signs of psychological stress'
)

interface = gr.TabbedInterface([text_interface, audio_interface], ['Text Analysis', 'Audio Analysis'])

# === 2. 修改啟動方式（關鍵步驟） ===
# 設定 Streamlit 頁面標題
st.set_page_config(page_title="Stress Detection App", layout="wide")

# inline=True 會讓 Gradio 直接生成一個可嵌入的本地網址
_, _, inline_url = interface.launch(inline=True, prevent_thread_lock=True)

# 使用 Streamlit 的 iframe 功能將 Gradio 介面顯示出來
st.title("Psychological Stress Detection System")
st.iframe(inline_url, height=800, scrolling=True)