# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zuRtoh5XitGDeZV9bgVN7_KS5ioXf_0
"""

import subprocess
import os

if not os.path.exists('gradio_running.txt'):
  with open('gradio_running.txt', 'w') as f:
    f.write('running')
  subprocess.Popen(['python', 'app.py'])