# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEJ-ZymkwnPoxAdPhknEfAKln9BXpOpx
"""

import pickle
import streamlit as st
import speech_recognition as sr

st.title('Psychological Stress Detection')

with open('vec.pkl', 'rb') as f:
  vec = pickle.load(f)

with open('model.pkl', 'rb') as f:
  model = pickle.load(f)

tab1, tab2 = st.tabs(['Text Analysis', 'Audio Analysis'])

with tab1:
  text_input = st.text_area('Text Input')
  submitted = st.button('Submit')

  if submitted:
    text_input_dt = vec.transform([text_input.strip()])
    text_pred = model.predict(text_input_dt.toarray())

    if text_pred == 1:
      st.write('Psychological Stress Detected')
    else:
      st.write('No Psychological Stress Detected')

with tab2:
  audio_input = st.file_uploader('Audio Input', type=['.wav', '.mp3'])
  submitted = st.button('Submit')

  if audio_input is not None:
    r = sr.Recognizer()
    with sr.AudioFile(audio_input) as source:
      audio = r.listen(source)
    audio_text = r.recognize_google(audio, language='en-US').strip()
    audio_input_dt = vec.transform([audio_text])
    audio_pred = model.predict(audio_input_dt.toarray())

    if audio_pred == 1:
      st.write('Psychological Stress Detected')
    else:
      st.write('No Psychological Stress Detected')
  else:
    st.stop()